import type * as React from "react";

type IconType = React.FC<React.SVGProps<SVGSVGElement>>;

// --------------------- IMPORTS ---------------------
import PlusIconRaw from "./plus.svg?react";
import CloseIconRaw from "./close.svg?react";
import BoxIconRaw from "./box.svg?react";
import CheckCircleIconRaw from "./check-circle.svg?react";
import AlertIconRaw from "./alert.svg?react";
import InfoIconRaw from "./info.svg?react";
import ErrorIconRaw from "./info-error.svg?react";
import BoltIconRaw from "./bolt.svg?react";
import ArrowUpIconRaw from "./arrow-up.svg?react";
import ArrowDownIconRaw from "./arrow-down.svg?react";
import FolderIconRaw from "./folder.svg?react";
import VideoIconRaw from "./videos.svg?react";
import AudioIconRaw from "./audio.svg?react";
import GridIconRaw from "./grid.svg?react";
import FileIconRaw from "./file.svg?react";
import DownloadIconRaw from "./download.svg?react";
import ArrowRightIconRaw from "./arrow-right.svg?react";
import GroupIconRaw from "./group.svg?react";
import BoxIconLineRaw from "./box-line.svg?react";
import ShootingStarIconRaw from "./shooting-star.svg?react";
import DollarLineIconRaw from "./dollar-line.svg?react";
import TrashBinIconRaw from "./trash.svg?react";
import AngleUpIconRaw from "./angle-up.svg?react";
import AngleDownIconRaw from "./angle-down.svg?react";
import PencilIconRaw from "./pencil.svg?react";
import CheckLineIconRaw from "./check-line.svg?react";
import CloseLineIconRaw from "./close-line.svg?react";
import ChevronDownIconRaw from "./chevron-down.svg?react";
import ChevronUpIconRaw from "./chevron-up.svg?react";
import PaperPlaneIconRaw from "./paper-plane.svg?react";
import LockIconRaw from "./lock.svg?react";
import EnvelopeIconRaw from "./envelope.svg?react";
import UserIconRaw from "./user-line.svg?react";
import CalenderIconRaw from "./calender-line.svg?react";
import EyeIconRaw from "./eye.svg?react";
import EyeCloseIconRaw from "./eye-close.svg?react";
import TimeIconRaw from "./time.svg?react";
import CopyIconRaw from "./copy.svg?react";
import ChevronLeftIconRaw from "./chevron-left.svg?react";
import UserCircleIconRaw from "./user-circle.svg?react";
import TaskIconRaw from "./task-icon.svg?react";
import ListIconRaw from "./list.svg?react";
import TableIconRaw from "./table.svg?react";
import PageIconRaw from "./page.svg?react";
import PieChartIconRaw from "./pie-chart.svg?react";
import BoxCubeIconRaw from "./box-cube.svg?react";
import PlugInIconRaw from "./plug-in.svg?react";
import DocsIconRaw from "./docs.svg?react";
import MailIconRaw from "./mail-line.svg?react";
import HorizontaLDotsRaw from "./horizontal-dots.svg?react";
import ChatIconRaw from "./chat.svg?react";
import AlertHexaIconRaw from "./alert-hexa.svg?react";
import ErrorHexaIconRaw from "./info-hexa.svg?react";
import MoreDotIconRaw from "./moredot.svg?react";
import AddProductIconRaw from "./box.svg?react";   
import AddCategories from "./add-cat.svg?react";   // <= AJOUTÉ  
// --------------------- EXPORTS TIPÉS ---------------------
export const PlusIcon: IconType = PlusIconRaw;
export const CloseIcon: IconType = CloseIconRaw;
export const BoxIcon: IconType = BoxIconRaw;
export const CheckCircleIcon: IconType = CheckCircleIconRaw;
export const AlertIcon: IconType = AlertIconRaw;
export const InfoIcon: IconType = InfoIconRaw;
export const ErrorIcon: IconType = ErrorIconRaw;
export const BoltIcon: IconType = BoltIconRaw;
export const ArrowUpIcon: IconType = ArrowUpIconRaw;
export const ArrowDownIcon: IconType = ArrowDownIconRaw;
export const FolderIcon: IconType = FolderIconRaw;
export const VideoIcon: IconType = VideoIconRaw;
export const AudioIcon: IconType = AudioIconRaw;
export const GridIcon: IconType = GridIconRaw;
export const FileIcon: IconType = FileIconRaw;
export const DownloadIcon: IconType = DownloadIconRaw;
export const ArrowRightIcon: IconType = ArrowRightIconRaw;
export const GroupIcon: IconType = GroupIconRaw;
export const BoxIconLine: IconType = BoxIconLineRaw;
export const ShootingStarIcon: IconType = ShootingStarIconRaw;
export const DollarLineIcon: IconType = DollarLineIconRaw;
export const TrashBinIcon: IconType = TrashBinIconRaw;
export const AngleUpIcon: IconType = AngleUpIconRaw;
export const AngleDownIcon: IconType = AngleDownIconRaw;
export const PencilIcon: IconType = PencilIconRaw;
export const CheckLineIcon: IconType = CheckLineIconRaw;
export const CloseLineIcon: IconType = CloseLineIconRaw;
export const ChevronDownIcon: IconType = ChevronDownIconRaw;
export const ChevronUpIcon: IconType = ChevronUpIconRaw;
export const PaperPlaneIcon: IconType = PaperPlaneIconRaw;
export const LockIcon: IconType = LockIconRaw;
export const EnvelopeIcon: IconType = EnvelopeIconRaw;
export const UserIcon: IconType = UserIconRaw;
export const CalenderIcon: IconType = CalenderIconRaw;
export const EyeIcon: IconType = EyeIconRaw;
export const EyeCloseIcon: IconType = EyeCloseIconRaw;
export const TimeIcon: IconType = TimeIconRaw;
export const CopyIcon: IconType = CopyIconRaw;
export const ChevronLeftIcon: IconType = ChevronLeftIconRaw;
export const UserCircleIcon: IconType = UserCircleIconRaw;
export const TaskIcon: IconType = TaskIconRaw;
export const ListIcon: IconType = ListIconRaw;
export const TableIcon: IconType = TableIconRaw;
export const PageIcon: IconType = PageIconRaw;
export const PieChartIcon: IconType = PieChartIconRaw;
export const BoxCubeIcon: IconType = BoxCubeIconRaw;
export const PlugInIcon: IconType = PlugInIconRaw;
export const DocsIcon: IconType = DocsIconRaw;
export const MailIcon: IconType = MailIconRaw;
export const HorizontaLDots: IconType = HorizontaLDotsRaw;
export const ChatIcon: IconType = ChatIconRaw;
export const AlertHexaIcon: IconType = AlertHexaIconRaw;
export const ErrorHexaIcon: IconType = ErrorHexaIconRaw;
export const MoreDotIcon: IconType = MoreDotIconRaw;
export const AddProductIcon: IconType = AddProductIconRaw;
export const AddCategoriesicon: IconType = AddCategories;